//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int PermissionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Resource { get; set; }
        public string Action { get; set; }
        public bool IsAllowed { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
